"""
Constants for Bible book mappings and outline heading levels.
"""

BOOK_ABBR = {
    "Genesis": "Gen",
    "Exodus": "Exo",
    "Leviticus": "Lev",
    "Numbers": "Num",
    "Deuteronomy": "Deut",
    "Joshua": "Josh",
    "Judges": "Judg",
    "Ruth": "Ruth",
    "1 Samuel": "1 Sam",
    "2 Samuel": "2 Sam",
    "1 Kings": "1 Kings",
    "2 Kings": "2 Kings",
    "1 Chronicles": "1 Chron",
    "2 Chronicles": "2 Chron",
    "Ezra": "Ezra",
    "Nehemiah": "Neh",
    "Esther": "Esth",
    "Job": "Job",
    "Psalms": "Psa",
    "Proverbs": "Prov",
    "Ecclesiastes": "Eccl",
    "Song of Solomon": "SoS",
    "Song of Songs": "SoS",
    "S.S": "SoS",
    "S.S.": "SoS",
    "S. S.": "SoS",
    "S. S": "SoS",
    "SS": "SoS",
    "Isaiah": "Isa",
    "Jeremiah": "Jer",
    "Lamentations": "Lam",
    "Ezekiel": "Ezek",
    "Daniel": "Dan",
    "Hosea": "Hosea",
    "Joel": "Joel",
    "Amos": "Amos",
    "Obadiah": "Obad",
    "Jonah": "Jonah",
    "Micah": "Micah",
    "Nahum": "Nah",
    "Habakkuk": "Hab",
    "Zephaniah": "Zep",
    "Haggai": "Hag",
    "Zechariah": "Zech",
    "Malachi": "Mal",
    "Matthew": "Matt",
    "Mark": "Mark",
    "Luke": "Luke",
    "John": "John",
    "Acts": "Acts",
    "Romans": "Rom",
    "1 Corinthians": "1 Cor",
    "2 Corinthians": "2 Cor",
    "Galatians": "Gal",
    "Ephesians": "Eph",
    "Philippians": "Phil",
    "Colossians": "Col",
    "1 Thessalonians": "1 Thes",
    "2 Thessalonians": "2 Thes",
    "1 Timothy": "1 Tim",
    "2 Timothy": "2 Tim",
    "Titus": "Titus",
    "Philemon": "Philem",
    "Hebrews": "Heb",
    "James": "James",
    "1 Peter": "1 Pet",
    "2 Peter": "2 Pet",
    "1 John": "1 John",
    "2 John": "2 John",
    "3 John": "3 John",
    "Jude": "Jude",
    "Revelation": "Rev"
}

JUBILEE_ABRV_TO_FULL_BOOK = {
    'Jon': 'Jonah',
    '2Pe': '2 Peter',
    '2Th': '2 Thessalonians',
    '2Jo': '2 John',
    'SoS': 'Song of Solomon',
    'Jud': 'Jude',
    'Jam': 'James',
    'Job': 'Job',
    '2Ki': '2 Kings',
    '1Co': '1 Corinthians',
    '2Ti': '2 Timothy',
    'Phi': 'Philippians',
    'Jdg': 'Judges',
    'Prv': 'Proverbs',
    'Isa': 'Isaiah',
    'Col': 'Colossians',
    'Deu': 'Deuteronomy',
    'Est': 'Esther',
    'Lam': 'Lamentations',
    'Mrk': 'Mark',
    '1Ch': '1 Chronicles',
    'Gen': 'Genesis',
    'Joh': 'John',
    'Exo': 'Exodus',
    'Jer': 'Jeremiah',
    'Hag': 'Haggai',
    'Joe': 'Joel',
    '1Sa': '1 Samuel',
    'Ecc': 'Ecclesiastes',
    '3Jo': '3 John',
    '2Co': '2 Corinthians',
    '1Ti': '1 Timothy',
    'Jos': 'Joshua',
    'Tit': 'Titus',
    'Zec': 'Zechariah',
    '1Pe': '1 Peter',
    'Luk': 'Luke',
    'Psa': 'Psalms',
    'Lev': 'Leviticus',
    'Oba': 'Obadiah',
    '1Ki': '1 Kings',
    '1Jo': '1 John',
    '1Th': '1 Thessalonians',
    'Phm': 'Philemon',
    'Rut': 'Ruth',
    'Hos': 'Hosea',
    'Gal': 'Galatians',
    'Mat': 'Matthew',
    'Zep': 'Zephaniah',
    'Num': 'Numbers',
    'Mic': 'Micah',
    'Hab': 'Habakkuk',
    'Eph': 'Ephesians',
    'Nah': 'Nahum',
    '2Sa': '2 Samuel',
    'Act': 'Acts',
    'Dan': 'Daniel',
    'Mal': 'Malachi',
    'Ezk': 'Ezekiel',
    '2Ch': '2 Chronicles',
    'Amo': 'Amos',
    'Neh': 'Nehemiah',
    'Heb': 'Hebrews',
    'Rom': 'Romans',
    'Rev': 'Revelation',
    'Ezr': 'Ezra'
}

BOOK_ABBR_INDEX = {
    "Gen": 1,
    "Exo": 2,
    "Lev": 3,
    "Num": 4,
    "Deut": 5,
    "Josh": 6,
    "Judg": 7,
    "Ruth": 8,
    "1 Sam": 9,
    "2 Sam": 10,
    "1 Kings": 11,
    "2 Kings": 12,
    "1 Chron": 13,
    "2 Chron": 14,
    "Ezra": 15,
    "Neh": 16,
    "Esth": 17,
    "Job": 18,
    "Psa": 19,
    "Prov": 20,
    "Eccl": 21,
    "SoS": 22,
    "Isa": 23,
    "Jer": 24,
    "Lam": 25,
    "Ezek": 26,
    "Dan": 27,
    "Hosea": 28,
    "Joel": 29,
    "Amos": 30,
    "Obad": 31,
    "Jonah": 32,
    "Micah": 33,
    "Nah": 34,
    "Hab": 35,
    "Zep": 36,
    "Hag": 37,
    "Zech": 38,
    "Mal": 39,
    "Matt": 40,
    "Mark": 41,
    "Luke": 42,
    "John": 43,
    "Acts": 44,
    "Rom": 45,
    "1 Cor": 46,
    "2 Cor": 47,
    "Gal": 48,
    "Eph": 49,
    "Phil": 50,
    "Col": 51,
    "1 Thes": 52,
    "2 Thes": 53,
    "1 Tim": 54,
    "2 Tim": 55,
    "Titus": 56,
    "Philem": 57,
    "Heb": 58,
    "James": 59,
    "1 Pet": 60,
    "2 Pet": 61,
    "1 John": 62,
    "2 John": 63,
    "3 John": 64,
    "Jude": 65,
    "Rev": 66,
}

# ONE_CHAPTER_BOOKS = {
#   "Obad",
#   "Philem",
#   "2 John",
#   "3 John",
#   "Jude",
# }

BOOK_ABBR_REVERSE = {v: (k if k != "SS" else "Song of Songs") for k, v in BOOK_ABBR.items()}
JUBILEE_ABRV_TO_FULL_BOOK_REVERSE = {v: k for k, v in JUBILEE_ABRV_TO_FULL_BOOK.items()}

OUTLINE_MAP = {
    "h1": "#",
    "tt": "##",
    "h5": "###",
    "del": "####",
    "var": "#####",
    "code": "######"
}
